# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(810, 489)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ifconfig_button = QtWidgets.QPushButton(self.centralwidget)
        self.ifconfig_button.setGeometry(QtCore.QRect(710, 10, 89, 31))
        self.ifconfig_button.setObjectName("ifconfig_button")
        self.traceroute_button = QtWidgets.QPushButton(self.centralwidget)
        self.traceroute_button.setGeometry(QtCore.QRect(10, 50, 89, 31))
        self.traceroute_button.setObjectName("traceroute_button")
        self.traceroute_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.traceroute_text.setGeometry(QtCore.QRect(110, 50, 541, 31))
        self.traceroute_text.setObjectName("traceroute_text")
        self.result = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(10, 130, 791, 351))
        self.result.setReadOnly(True)
        self.result.setObjectName("result")
        self.getmac_button = QtWidgets.QPushButton(self.centralwidget)
        self.getmac_button.setGeometry(QtCore.QRect(710, 50, 91, 31))
        self.getmac_button.setObjectName("getmac_button")
        self.nmblookup_button = QtWidgets.QPushButton(self.centralwidget)
        self.nmblookup_button.setGeometry(QtCore.QRect(10, 10, 91, 31))
        self.nmblookup_button.setObjectName("nmblookup_button")
        self.nmblookup_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.nmblookup_text.setGeometry(QtCore.QRect(110, 10, 541, 31))
        self.nmblookup_text.setObjectName("nmblookup_text")
        self.ping_button = QtWidgets.QPushButton(self.centralwidget)
        self.ping_button.setGeometry(QtCore.QRect(10, 90, 89, 31))
        self.ping_button.setObjectName("ping_button")
        self.ping_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.ping_text.setGeometry(QtCore.QRect(110, 90, 541, 31))
        self.ping_text.setObjectName("ping_text")
        self.route_button = QtWidgets.QPushButton(self.centralwidget)
        self.route_button.setGeometry(QtCore.QRect(710, 90, 91, 31))
        self.route_button.setObjectName("route_button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ifconfig_button.setText(_translate("MainWindow", "ifconfig"))
        self.traceroute_button.setText(_translate("MainWindow", "traceroute"))
        self.traceroute_text.setPlainText(_translate("MainWindow", "ya.ru"))
        self.getmac_button.setText(_translate("MainWindow", "getmac"))
        self.nmblookup_button.setText(_translate("MainWindow", "nmblookup"))
        self.nmblookup_text.setPlainText(_translate("MainWindow", "-A 127.0.0.1"))
        self.ping_button.setText(_translate("MainWindow", "ping"))
        self.ping_text.setPlainText(_translate("MainWindow", "google.com"))
        self.route_button.setText(_translate("MainWindow", "route"))
